export const counterActions = {
    INCREASE: "COUNTER_INCREASE",
    DECREASE: "COUNTER_DECREASE"
}

export const newsActions = {
    GET_LATEST: "NEWS_GET_LATEST",
    GET_POPULAR: "NEWS_GET_POPULAR",
    SET_LATEST: "NEWS_SET_LATEST",
    SET_POPULAR: "NEWS_SET_POPULAR",
}

export const errorActions = {
    SET_LATEST_ERROR: "NEWS_SET_LATEST_ERROR",
    SET_POPULAR_ERROR: "NEWS_SET_POPULAR_ERROR",
}


